USE [SSManagementDEV]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[usp_SaveOutward]
(
    @Mode NVARCHAR(10),                         -- INSERT / UPDATE
    @OutwardId INT = NULL OUTPUT,
    @CompanyId INT,
    @Colour NVARCHAR(50),
    @DesignName NVARCHAR(100),
    @StyleNo NVARCHAR(50),
    @UploadURL NVARCHAR(255),
    @CreatedBy NVARCHAR(100),

    -- DC number is generated by C# and passed as INPUT
    @OutwardDcNo NVARCHAR(50),

    @Status NVARCHAR(50),
    @DeliveryTo NVARCHAR(150) = NULL,
    @PoNo NVARCHAR(100) = NULL,
    @Weight NVARCHAR(100) = NULL,
    @NoOfBundles NVARCHAR(100) = NULL,
    @Remarks NVARCHAR(MAX) = NULL,
    @SelectedDcNos NVARCHAR(MAX) = NULL,
    @SizeData NVARCHAR(MAX)
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRY

        BEGIN TRANSACTION;

        DECLARE @SuccessMessage NVARCHAR(100);

        ---------------------------------------------------------
        -- 1. VALIDATE MODE
        ---------------------------------------------------------

        IF UPPER(LTRIM(RTRIM(ISNULL(@Mode, '')))) NOT IN ('INSERT', 'UPDATE')
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'Invalid Mode. Only INSERT or UPDATE is allowed.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        ---------------------------------------------------------
        -- 2. BASIC VALIDATIONS
        ---------------------------------------------------------

        IF @CompanyId IS NULL OR @CompanyId <= 0
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'Invalid CompanyId.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        IF NULLIF(LTRIM(RTRIM(@StyleNo)), '') IS NULL
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'StyleNo is required.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        IF NULLIF(LTRIM(RTRIM(@DesignName)), '') IS NULL
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'DesignName is required.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        IF NULLIF(LTRIM(RTRIM(@CreatedBy)), '') IS NULL
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'CreatedBy is required.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        IF NULLIF(LTRIM(RTRIM(@Status)), '') IS NULL
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'Status is required.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        ---------------------------------------------------------
        -- 3. DC NUMBER VALIDATION
        --
        -- DC number MUST come from C#
        -- SP will NOT generate it.
        ---------------------------------------------------------

        IF UPPER(LTRIM(RTRIM(@Mode))) = 'INSERT'
        BEGIN

            IF NULLIF(LTRIM(RTRIM(@OutwardDcNo)), '') IS NULL
            BEGIN
                ROLLBACK TRANSACTION;

                SELECT
                    0 AS Success,
                    'Outward DC Number is required for INSERT.' AS Message,
                    NULL AS OutwardId,
                    NULL AS OutwardDcNo;

                RETURN;
            END;

        END;


        ---------------------------------------------------------
        -- 4. SIZE DATA VALIDATION
        ---------------------------------------------------------

        IF NULLIF(LTRIM(RTRIM(@SizeData)), '') IS NULL
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'SizeData is required.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        IF ISJSON(@SizeData) <> 1
        BEGIN
            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'Invalid SizeData JSON.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;
        END;


        ---------------------------------------------------------
        -- 5. INPUT SIZE TABLE
        ---------------------------------------------------------

        DECLARE @InputSizes TABLE
        (
            StyleNo NVARCHAR(50),
            DesignName NVARCHAR(100),
            Colour NVARCHAR(50),
            Size NVARCHAR(20),
            Count INT
        );


        ---------------------------------------------------------
        -- 6. EXTRACT MULTI-COLOUR JSON
        --
        -- Expected JSON:
        --
        -- {
        --   "colourBreakdowns": [
        --     {
        --       "colour": "RED",
        --       "sizes": [
        --         {
        --           "size": "M",
        --           "count": 2
        --         }
        --       ]
        --     },
        --     {
        --       "colour": "MAROON",
        --       "sizes": [
        --         {
        --           "size": "M",
        --           "count": 2
        --         }
        --       ]
        --     }
        --   ]
        -- }
        ---------------------------------------------------------

        IF JSON_QUERY(@SizeData, '$.colourBreakdowns') IS NOT NULL
        BEGIN

            INSERT INTO @InputSizes
            (
                StyleNo,
                DesignName,
                Colour,
                Size,
                Count
            )
            SELECT
                @StyleNo,
                @DesignName,
                LTRIM(RTRIM(c.Colour)),
                LTRIM(RTRIM(s.Size)),
                s.Count
            FROM OPENJSON(@SizeData, '$.colourBreakdowns')
            WITH
            (
                Colour NVARCHAR(50) '$.colour',
                Sizes NVARCHAR(MAX) '$.sizes' AS JSON
            ) c
            CROSS APPLY OPENJSON(c.Sizes)
            WITH
            (
                Size NVARCHAR(20) '$.size',
                Count INT '$.count'
            ) s
            WHERE
                ISNULL(s.Count, 0) > 0
                AND NULLIF(LTRIM(RTRIM(c.Colour)), '') IS NOT NULL
                AND NULLIF(LTRIM(RTRIM(s.Size)), '') IS NOT NULL;


            -----------------------------------------------------
            -- For MULTI colour:
            -- Store actual colours in main Outward.Colour
            --
            -- Example:
            -- RED, MAROON
            -----------------------------------------------------

            IF
            (
                UPPER(LTRIM(RTRIM(ISNULL(@Colour, '')))) = 'MULTI'
                OR NULLIF(LTRIM(RTRIM(@Colour)), '') IS NULL
            )
            BEGIN

                SELECT
                    @Colour =
                        LEFT
                        (
                            STUFF
                            (
                                (
                                    SELECT
                                        ', ' + C.Colour
                                    FROM
                                    (
                                        SELECT DISTINCT
                                            LTRIM(RTRIM(Colour)) AS Colour
                                        FROM @InputSizes
                                        WHERE
                                            NULLIF(LTRIM(RTRIM(Colour)), '') IS NOT NULL
                                    ) C
                                    ORDER BY C.Colour
                                    FOR XML PATH('')
                                ),
                                1,
                                2,
                                ''
                            ),
                            50
                        );

            END;

        END


        ---------------------------------------------------------
        -- 7. LEGACY SINGLE COLOUR JSON
        ---------------------------------------------------------

        ELSE IF JSON_QUERY(@SizeData, '$.sizes') IS NOT NULL
        BEGIN

            INSERT INTO @InputSizes
            (
                StyleNo,
                DesignName,
                Colour,
                Size,
                Count
            )
            SELECT
                @StyleNo,
                @DesignName,
                LTRIM(RTRIM(@Colour)),
                LTRIM(RTRIM(Size)),
                Count
            FROM OPENJSON(@SizeData, '$.sizes')
            WITH
            (
                Size NVARCHAR(20) '$.size',
                Count INT '$.count'
            )
            WHERE
                ISNULL(Count, 0) > 0
                AND NULLIF(LTRIM(RTRIM(Size)), '') IS NOT NULL;

        END;


        ---------------------------------------------------------
        -- 8. VALIDATE INPUT SIZES
        ---------------------------------------------------------

        IF NOT EXISTS
        (
            SELECT 1
            FROM @InputSizes
        )
        BEGIN

            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'At least one colour and size must be provided with count > 0.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;

        END;


        ---------------------------------------------------------
        -- 9. VALIDATE COLOUR
        ---------------------------------------------------------

        IF NULLIF(LTRIM(RTRIM(@Colour)), '') IS NULL
        BEGIN

            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'Colour is required.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;

        END;


        ---------------------------------------------------------
        -- 10. VALIDATE DUPLICATE COLOUR + SIZE
        ---------------------------------------------------------

        IF EXISTS
        (
            SELECT
                Colour,
                Size
            FROM @InputSizes
            GROUP BY
                Colour,
                Size
            HAVING COUNT(*) > 1
        )
        BEGIN

            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                'Duplicate sizes found within a single colour.' AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;

        END;


        ---------------------------------------------------------
        -- 11. GET INWARD STOCK
        ---------------------------------------------------------

        DECLARE @Inward TABLE
        (
            StyleNo NVARCHAR(50),
            DesignName NVARCHAR(100),
            Colour NVARCHAR(50),
            Size NVARCHAR(20),
            TotalInward INT
        );


        INSERT INTO @Inward
        (
            StyleNo,
            DesignName,
            Colour,
            Size,
            TotalInward
        )
        SELECT
            StyleNo,
            DesignName,
            Colour,
            Size,
            SUM(ISNULL([Count], 0))
        FROM dbo.InwardSizeCount
        WHERE
            StyleNo = @StyleNo
            AND DesignName = @DesignName
        GROUP BY
            StyleNo,
            DesignName,
            Colour,
            Size;


        ---------------------------------------------------------
        -- 12. GET ALREADY USED OUTWARD STOCK
        --
        -- During UPDATE exclude current OutwardId.
        ---------------------------------------------------------

        DECLARE @OutwardUsed TABLE
        (
            StyleNo NVARCHAR(50),
            DesignName NVARCHAR(100),
            Colour NVARCHAR(50),
            Size NVARCHAR(20),
            TotalOutward INT
        );


        INSERT INTO @OutwardUsed
        (
            StyleNo,
            DesignName,
            Colour,
            Size,
            TotalOutward
        )
        SELECT
            StyleNo,
            DesignName,
            Colour,
            Size,
            SUM(ISNULL([Count], 0))
        FROM dbo.OutwardSizeCount
        WHERE
            (
                UPPER(LTRIM(RTRIM(@Mode))) = 'INSERT'
                OR OutwardId <> @OutwardId
            )
            AND StyleNo = @StyleNo
            AND DesignName = @DesignName
        GROUP BY
            StyleNo,
            DesignName,
            Colour,
            Size;


        ---------------------------------------------------------
        -- 13. CALCULATE AVAILABLE STOCK
        ---------------------------------------------------------

        DECLARE @Available TABLE
        (
            StyleNo NVARCHAR(50),
            DesignName NVARCHAR(100),
            Colour NVARCHAR(50),
            Size NVARCHAR(20),
            AvailableCount INT
        );


        INSERT INTO @Available
        (
            StyleNo,
            DesignName,
            Colour,
            Size,
            AvailableCount
        )
        SELECT
            i.StyleNo,
            i.DesignName,
            i.Colour,
            i.Size,
            ISNULL(i.TotalInward, 0)
            -
            ISNULL(o.TotalOutward, 0)
        FROM @Inward i
        LEFT JOIN @OutwardUsed o
            ON  i.StyleNo = o.StyleNo
            AND i.DesignName = o.DesignName
            AND i.Colour = o.Colour
            AND i.Size = o.Size;


        ---------------------------------------------------------
        -- 14. STOCK VALIDATION
        ---------------------------------------------------------

        DECLARE @ErrorMsg NVARCHAR(MAX);


        SELECT
            @ErrorMsg =
                STRING_AGG
                (
                    'Colour ' + i.Colour
                    + ' Size ' + i.Size
                    + ' Available: '
                    + CAST(ISNULL(a.AvailableCount, 0) AS VARCHAR(20))
                    + ' Given: '
                    + CAST(i.Count AS VARCHAR(20)),
                    ' | '
                )
        FROM @InputSizes i
        LEFT JOIN @Available a
            ON  i.StyleNo = a.StyleNo
            AND i.DesignName = a.DesignName
            AND i.Colour = a.Colour
            AND i.Size = a.Size
        WHERE
            i.Count > ISNULL(a.AvailableCount, 0);


        IF @ErrorMsg IS NOT NULL
        BEGIN

            ROLLBACK TRANSACTION;

            SELECT
                0 AS Success,
                @ErrorMsg AS Message,
                NULL AS OutwardId,
                NULL AS OutwardDcNo;

            RETURN;

        END;


        ---------------------------------------------------------
        -- 15. INSERT MODE
        --
        -- IMPORTANT:
        -- DC NUMBER IS NOT GENERATED HERE.
        --
        -- C# generates:
        -- SSE-1014/2026-2027
        --
        -- C# passes it through @OutwardDcNo.
        ---------------------------------------------------------

        IF UPPER(LTRIM(RTRIM(@Mode))) = 'INSERT'
        BEGIN

            -----------------------------------------------------
            -- Validate DC number received from C#
            -----------------------------------------------------

            IF NULLIF(LTRIM(RTRIM(@OutwardDcNo)), '') IS NULL
            BEGIN

                ROLLBACK TRANSACTION;

                SELECT
                    0 AS Success,
                    'Outward DC Number is required.' AS Message,
                    NULL AS OutwardId,
                    NULL AS OutwardDcNo;

                RETURN;

            END;


            -----------------------------------------------------
            -- CHECK DUPLICATE DC NUMBER
            --
            -- We are NOT generating the DC here.
            -- We only make sure the C# generated DC does not
            -- already exist.
            -----------------------------------------------------

            IF EXISTS
            (
                SELECT 1
                FROM dbo.Outward WITH (UPDLOCK, HOLDLOCK)
                WHERE
                    OutwardDcNo = @OutwardDcNo
            )
            BEGIN

                ROLLBACK TRANSACTION;

                SELECT
                    0 AS Success,
                    'Outward DC Number already exists: '
                    + @OutwardDcNo AS Message,
                    NULL AS OutwardId,
                    NULL AS OutwardDcNo;

                RETURN;

            END;


            -----------------------------------------------------
            -- INSERT OUTWARD HEADER
            --
            -- ONLY ONE HEADER INSERT
            --
            -- RED + MAROON
            --       ↓
            -- ONE OutwardId
            --       ↓
            -- ONE DC NUMBER
            -----------------------------------------------------

            INSERT INTO dbo.Outward
            (
                CompanyId,
                Colour,
                DesignName,
                StyleNo,
                UploadURL,
                CreatedBy,
                OutwardDcNo,
                Status,
                DeliveryTo,
                PoNo,
                Weight,
                NoOfBundles,
                Remarks,
                SelectedDcNos
            )
            VALUES
            (
                @CompanyId,
                @Colour,
                @DesignName,
                @StyleNo,
                @UploadURL,
                @CreatedBy,
                @OutwardDcNo,
                @Status,
                @DeliveryTo,
                @PoNo,
                @Weight,
                @NoOfBundles,
                @Remarks,
                @SelectedDcNos
            );


            -----------------------------------------------------
            -- GET GENERATED OUTWARD ID
            -----------------------------------------------------

            SET @OutwardId =
                CONVERT(INT, SCOPE_IDENTITY());


            IF @OutwardId IS NULL OR @OutwardId <= 0
            BEGIN

                THROW 50001,
                      'Outward header was not inserted.',
                      1;

            END;


            -----------------------------------------------------
            -- INSERT ALL COLOURS
            --
            -- Example:
            --
            -- OutwardId    Colour
            -- -------------------
            -- 4621         RED
            -- 4621         MAROON
            -----------------------------------------------------

            INSERT INTO dbo.OutwardColour
            (
                OutwardId,
                Colour
            )
            SELECT DISTINCT
                @OutwardId,
                LTRIM(RTRIM(Colour))
            FROM @InputSizes
            WHERE
                NULLIF(LTRIM(RTRIM(Colour)), '') IS NOT NULL;


            IF NOT EXISTS
            (
                SELECT 1
                FROM dbo.OutwardColour
                WHERE OutwardId = @OutwardId
            )
            BEGIN

                THROW 50002,
                      'Outward saved but colour details were not inserted.',
                      1;

            END;


            -----------------------------------------------------
            -- INSERT ALL SIZE DETAILS
            --
            -- Same OutwardId for all colours.
            -----------------------------------------------------

            INSERT INTO dbo.OutwardSizeCount
            (
                OutwardId,
                OutwardColourId,
                StyleNo,
                DesignName,
                Colour,
                Size,
                Count
            )
            SELECT
                @OutwardId,
                oc.OutwardColourId,
                i.StyleNo,
                i.DesignName,
                i.Colour,
                i.Size,
                i.Count
            FROM @InputSizes i
            INNER JOIN dbo.OutwardColour oc
                ON  oc.OutwardId = @OutwardId
                AND LTRIM(RTRIM(oc.Colour))
                    = LTRIM(RTRIM(i.Colour));


            -----------------------------------------------------
            -- VALIDATE SIZE DETAILS
            -----------------------------------------------------

            IF NOT EXISTS
            (
                SELECT 1
                FROM dbo.OutwardSizeCount
                WHERE OutwardId = @OutwardId
            )
            BEGIN

                THROW 50003,
                      'Outward header was created but size details were not inserted.',
                      1;

            END;


            -----------------------------------------------------
            -- SUCCESS MESSAGE (SELECT moved to end)
            -----------------------------------------------------

            SET @SuccessMessage = 'Outward saved successfully';

        END


        ---------------------------------------------------------
        -- 16. UPDATE MODE
        ---------------------------------------------------------

        ELSE IF UPPER(LTRIM(RTRIM(@Mode))) = 'UPDATE'
        BEGIN

            -----------------------------------------------------
            -- Validate OutwardId
            -----------------------------------------------------

            IF @OutwardId IS NULL OR @OutwardId <= 0
            BEGIN

                ROLLBACK TRANSACTION;

                SELECT
                    0 AS Success,
                    'Invalid OutwardId for UPDATE.' AS Message,
                    NULL AS OutwardId,
                    NULL AS OutwardDcNo;

                RETURN;

            END;


            -----------------------------------------------------
            -- Get existing DC number
            --
            -- NEVER generate a new DC on UPDATE.
            -----------------------------------------------------

            SELECT
                @OutwardDcNo = OutwardDcNo
            FROM dbo.Outward WITH (UPDLOCK, HOLDLOCK)
            WHERE
                OutwardId = @OutwardId;


            -----------------------------------------------------
            -- Validate existing record
            -----------------------------------------------------

            IF NULLIF(LTRIM(RTRIM(@OutwardDcNo)), '') IS NULL
            BEGIN

                ROLLBACK TRANSACTION;

                SELECT
                    0 AS Success,
                    'Existing Outward DC Number was not found.' AS Message,
                    NULL AS OutwardId,
                    NULL AS OutwardDcNo;

                RETURN;

            END;


            -----------------------------------------------------
            -- UPDATE OUTWARD HEADER
            --
            -- DC NUMBER IS NOT CHANGED.
            -----------------------------------------------------

            UPDATE dbo.Outward
            SET
                CompanyId = @CompanyId,
                Colour = @Colour,
                DesignName = @DesignName,
                StyleNo = @StyleNo,
                UploadURL = @UploadURL,
                Status = @Status,
                DeliveryTo = @DeliveryTo,
                PoNo = @PoNo,
                Weight = @Weight,
                NoOfBundles = @NoOfBundles,
                Remarks = @Remarks,
                SelectedDcNos = @SelectedDcNos,
                UpdatedDate = GETDATE()
            WHERE
                OutwardId = @OutwardId;


            -----------------------------------------------------
            -- DELETE OLD SIZE DATA
            -----------------------------------------------------

            DELETE FROM dbo.OutwardSizeCount
            WHERE
                OutwardId = @OutwardId;


            -----------------------------------------------------
            -- DELETE OLD COLOUR DATA
            -----------------------------------------------------

            DELETE FROM dbo.OutwardColour
            WHERE
                OutwardId = @OutwardId;


            -----------------------------------------------------
            -- INSERT UPDATED COLOURS
            -----------------------------------------------------

            INSERT INTO dbo.OutwardColour
            (
                OutwardId,
                Colour
            )
            SELECT DISTINCT
                @OutwardId,
                LTRIM(RTRIM(Colour))
            FROM @InputSizes
            WHERE
                NULLIF(LTRIM(RTRIM(Colour)), '') IS NOT NULL;


            -----------------------------------------------------
            -- INSERT UPDATED SIZE DETAILS
            -----------------------------------------------------

            INSERT INTO dbo.OutwardSizeCount
            (
                OutwardId,
                OutwardColourId,
                StyleNo,
                DesignName,
                Colour,
                Size,
                Count
            )
            SELECT
                @OutwardId,
                oc.OutwardColourId,
                i.StyleNo,
                i.DesignName,
                i.Colour,
                i.Size,
                i.Count
            FROM @InputSizes i
            INNER JOIN dbo.OutwardColour oc
                ON  oc.OutwardId = @OutwardId
                AND LTRIM(RTRIM(oc.Colour))
                    = LTRIM(RTRIM(i.Colour));


            -----------------------------------------------------
            -- VALIDATE UPDATED DETAILS
            -----------------------------------------------------

            IF NOT EXISTS
            (
                SELECT 1
                FROM dbo.OutwardSizeCount
                WHERE OutwardId = @OutwardId
            )
            BEGIN

                THROW 50004,
                      'Outward updated but size details were not inserted.',
                      1;

            END;


            -----------------------------------------------------
            -- SUCCESS MESSAGE (SELECT moved to end)
            -----------------------------------------------------

            SET @SuccessMessage = 'Outward updated successfully';

        END;


        ---------------------------------------------------------
        -- 17. UPDATE INWARD / OUTWARD STATUS
        --
        -- Execute only after complete save succeeds.
        ---------------------------------------------------------

        EXEC dbo.PR_UPDATE_INWARD_OUTWARD_STATUS
            @OutwardId,
            @OutwardDcNo;


        ---------------------------------------------------------
        -- 18. COMMIT
        ---------------------------------------------------------

        COMMIT TRANSACTION;

        ---------------------------------------------------------
        -- 19. RETURN SUCCESS
        ---------------------------------------------------------
        SELECT
            1 AS Success,
            @SuccessMessage AS Message,
            @OutwardId AS OutwardId,
            @OutwardDcNo AS OutwardDcNo;

    END TRY

    BEGIN CATCH

        ---------------------------------------------------------
        -- ROLLBACK EVERYTHING
        ---------------------------------------------------------

        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;


        ---------------------------------------------------------
        -- RETURN ERROR
        ---------------------------------------------------------

        SELECT
            0 AS Success,
            ERROR_MESSAGE() AS Message,
            NULL AS OutwardId,
            NULL AS OutwardDcNo;

    END CATCH;

END;
GO
