name: API Auto Deploy

on:
  push:
    branches:
      - dev
      - test

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish --configuration Release --output publish

      - name: Deploy DEV
        shell: powershell
        run: C:\Deploy\deploy-api-dev.ps1

  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish --configuration Release --output publish

      - name: Deploy TEST
        shell: powershell
        run: C:\Deploy\deploy-api-test.ps1